const char INDEX_HTML[] =
"<!DOCTYPE HTML>"
"<html>"
"<head>"
"<meta content=\"text/html; charset=ISO-8859-1\""
"http-equiv=\"content-type\">"
"<meta name = \"viewport\" content = \"width = device-width, initial-scale = 1.0, maximum-scale = 1.0, user-scalable=0\">"
"<title>AirManager Credential page</title>"
"<style>"
"\"body { background-color: #808080; font-family: Arial, Helvetica, Sans-Serif; Color: #000000; text-align:center;}\""
"</style>"
"</head>"
"<body>"
"<h3>Enter your WiFi and MQTT credentials</h3>"
"<form action=\"/\" method=\"post\">"
"<p>"
"<label>WIFI SSID:&nbsp;</label>"
"<input maxlength=\"50\" name=\"wifi_ssid\"><br>"
"<label>WIFI Key:&nbsp;&nbsp;&nbsp;&nbsp;</label>"
"<input maxlength=\"50\" name=\"wifi_pwd\"><br>"
"</p>"
"<p>"
"<label>MQTT Address:&nbsp;</label>"
"<input maxlength=\"50\" name=\"mqtt_addr\"><br>"
"<label>MQTT Port:&nbsp;</label>"
"<input maxlength=\"5\" name=\"mqtt_port\"><br>"
"<label>MQTT User:&nbsp;</label>"
"<input maxlength=\"50\" name=\"mqtt_user\"><br>"
"<label>MQTT password:&nbsp;&nbsp;&nbsp;&nbsp;</label>"
"<input maxlength=\"50\" name=\"mqtt_pwd\"><br>"
"</p>"
"<input type=\"submit\" value=\"Save\">"
"</form>"
"</body>"
"</html>";
